### ISSUE TITLE
Slack IRC client fails to start

### ISSUE THREAD

**Issue by ddinh** [aeirola/slack-irc-client#1]
Here's the terminal output with --verbose:

```
info: Starting slack-irc-client
verbose: Starting Slack listener
verbose: Binding Slack event handler
info: Connecting to Slack...
verbose: attempting to connect via the RTM API
verbose: Starting terminal listener

/usr/local/lib/node_modules/slack-irc-client/lib/terminal-listener.js:15
    context.terminal.events = new EventEmitter();
                              ^
TypeError: object is not a function
    at Object.initTerminaListener [as init] (/usr/local/lib/node_modules/slack-irc-client/lib/terminal-listener.js:15:31)
    at start (/usr/local/lib/node_modules/slack-irc-client/bin/server.js:81:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/slack-irc-client/bin/server.js:84:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

Box is running Ubuntu 14.04.3 and node v0.10.25.

**Comment by aeirola** [comment]
slack-irc-client only support node 0.12 and up. This is mainly due to one of the main dependencies, node-slack-client depending on node version 0.12 (https://github.com/slackhq/node-slack-client/blob/master/package.json#L49). I'll mention this in the documentation, and add some version check to startup.

**Comment by aeirola** [comment]
Apprently there doesn't seem to be any hard dependencies on 0.12, so I'll just fix this issue and hope it works well on 0.10. Released version 0.1.4 with the fix.
